name: Extract Source Artifact
description: Extracts artifacts from an existing Docker image to be used for from source installation
inputs:
  digest:
    description: Digest of Docker image to use
    required: true
  architecture:
    description: Name of architecture, will be used to create directories (e.g. x64, arm64)
    required: true
  release-tag:
    description: Tag of the release to which the artifact will be attached
    required: true
  repository:
    description: Repository to which the release belongs, e.g. owner/repo
    required: true
  token:
    description: GitHub token with permissions to upload release assets
    required: true
runs:
  using: "composite"
  steps:
    - name: Prebuilt debian dependencies
      uses: Meierschlumpf/homarr/.github/actions/prebuilt-debian@dev
      id: prebuilt-debian
      with:
        architecture: ${{ inputs.architecture }}
    - name: Start docker container for ${{ inputs.architecture }}
      run: |
        docker run --name homarr \
          -e "SECRET_ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000" \
          --detach --rm ${{ inputs.digest }}
      shell: bash
    - name: Extract source from ${{ inputs.architecture }} container
      run: |
        docker cp ${{ steps.prebuilt-debian.outputs.path }} homarr:/app/build/debian && \
        docker exec homarr cp /etc/nginx/templates/nginx.conf /app && \
        docker exec homarr tar -czf extraction.tar.gz -C /app . && \
        mkdir -p ${{ runner.temp }}/extraction/${{ inputs.architecture }} && \
        docker cp homarr:/app/extraction.tar.gz ${{ runner.temp }}/extraction/${{ inputs.architecture }}/source-${{ inputs.architecture }}.tar.gz
      shell: bash
    - name: Stop ${{ inputs.architecture }} container
      if: always()
      run: docker container remove --force --volumes homarr
      shell: bash
    - name: Add source archive to release
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: gh release upload --repo ${{ inputs.repository }} ${{ inputs.release-tag }} ${{ runner.temp }}/extraction/${{ inputs.architecture }}/source-${{ inputs.architecture }}.tar.gz --clobber
      shell: bash
